name: Run Azure Login with OpenID Connect
on: [push]

permissions: write-all
      
jobs: 
  build-and-deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
    - name: 'Run Azure CLI commands'
      run: |
          az network vnet create -g maria -n MyVnet1
          az group list
          pwd